### PR TITLE
fix(287): log4js error - this.log is not a function

### LINKED ISSUE #287: this.log is not a function
The `safe-logger.js` used in this project looses the context information (`this` reference, prototype) about the provided logger.
So if you use something like `log4js` (latest version) as a logger for authmosphere - it will error out with message: `this.log is not a function`.
A link to related issue in log4js: https://github.com/log4js-node/log4js-node/issues/979

### PR DESCRIPTION
**Pull request by bezrodnov**
close #287

### CODE REVIEW

**Comment by bezrodnov** [comment]
:+1:

**Comment by bezrodnov** [comment]
:+1:

**Comment by Retro64** [comment]
@bezrodnov could you bump the version to 4.2.0? Looks good to us

**Comment by bezrodnov** [comment]
@Retro64 done. Thank you for the review!

**Comment by Retro64** [comment]
:+1:

**Comment by Retro64** [comment]
:+1:

**Comment by bezrodnov** [comment]
:+1:

**Comment by ISO50** [comment]
👍

**Pull request merged**
