### PR TITLE
110 improve oauth config type

### PR DESCRIPTION
**Pull request by awaltert**
See #110 

I introduced `OAuthGrantType` as string enum, which substitutes the string constants declared in `constants.ts`. This was necessary, as I refactored OAuthConfig to be a union composed from tagged unions. Thus, the enum is used both as type and as value.

Please have a look at the changes and let me know what you think 😄

### CODE REVIEW

**Comment by bzums** [comment]
Looks good to me so far, thanks for the contribution 👍  :)
Question now is whether this change is breaking. `OAuthConfig` was exported and may be used, are there valid configs which would now lead to problems? Could be, right?

**Comment by awaltert** [comment]
@bzums That's a really good question. From what I have seen so far, the changed definition for `OAuthConfig` is not necessarily breaking, as the tagged unions describes in more detail, what was intended even before. 

As far as I understand, each request should be routed through `validateOAuthConfig` which in turn expects a param of type `OAuthConfig`. In this functions the expected combination of properties in dependency of the config type and checks now both during runtime and compile time thanks to the type guards of the tagged union types. Thus, we should be pretty save here. :smile:

In my opinion, the type change of `queryParams` is more like a breaking change because it is much stricter than before.

So, I'm unsure, should we handle this change as breaking?

**Comment by bzums** [comment]
I think it would be consistent and reasonable to consider this change breaking. The question is imo then whether we want to wait for some other (breaking) features planned for the near future (e.g. https://github.com/zalando-incubator/authmosphere/issues/60) and create a new 2.x.x release instead of creating multiple major versions now. What do you think @awaltert @ISO50 @Retro64 ?

Independent of that the docs should be adapted, but other than that i am fine with this change :) 👍

**Comment by ISO50** [comment]
@bzums I prefer to not release breaking versions too often.

**Comment by ISO50** [comment]
@awaltert by the way feel free to include a patch for the contributing section in `package.json` as well ;)

**Comment by awaltert** [comment]
@ISO50 @Retro64 @bzums Please review the changes I made in the `readme.md` to describe the new `OAuthConfig` type and let me know if I missed something 😄

**Comment by bzums** [comment]
@awaltert looks good to me so far. Since this is breaking we thought it would be a good idea to keep this PR open until https://github.com/zalando-incubator/authmosphere/issues/118 is tackled, since that ticket will also introduce a lot of changes and should probably be build on this change. Do you agree? @ISO50 @Retro64

**Comment by bzums** [comment]
@awaltert we created a branch for version 2.0.0 in which we want to merge a number of breaking changes, including this PR if possible. Can you create a new PR against https://github.com/zalando-incubator/authmosphere/tree/authmosphere-2-0-0? That would be great :) (afterwards we would close this PR)

**Comment by ISO50** [comment]
👍

**Comment by Retro64** [comment]
:+1:

**Comment by bzums** [comment]
👍

**Pull request merged**
