### PR TITLE
fix(deps): Update dependencies

### LINKED ISSUE #231: Fix possible vulnerabilities
update lodash and just-extend

### PR DESCRIPTION
**Pull request by Retro64**
close #231

### CODE REVIEW

**Comment by Retro64** [comment]
:+1:

**Comment by ISO50** [comment]
👍

**Comment by Retro64** [comment]
:+1:

**Comment by ISO50** [comment]
👍

**Comment by bzums** [comment]
The version should also be updated here imo (bugfix version),  what do you think?  Otherwise changes are not visible for consumers.

**Comment by Retro64** [comment]
> The version should also be updated here imo (bugfix version), what do you think? Otherwise changes are not visible for consumers.

true

**Comment by Retro64** [comment]
:+1:

**Comment by ISO50** [comment]
👍

**Pull request merged**
